### ISSUE TITLE
Version 4.11 and 4.12 missing

### ISSUE THREAD

**Issue by martinvenus** [cptactionhank/docker-atlassian-bitbucket#5]
Hi,

version 4.11 and also 4.12 has been released some time ago, but no image has been released.

There are some nice features in 4.11. Could I help somehow to prepare version 4.11 and 4.12?

Thank you very much.

**Comment by cptactionhank** [comment]
Thank you for reporting this CI/CD automation loop had been down for a month or two so some versions got skipped :( I'll look into getting these versions back in the repository
